patientregistration/Controllers/PdeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class PdeleteController : Controller
    {
        clinicEntities dbobj = new clinicEntities();
        // GET: Pdelete
        public ActionResult delload(Class4 obj)
        {
            if (ModelState.IsValid)
            {
                dbobj.sp_delete(Session["FullName"].ToString());

                obj.msg = "Successfully deleted";
                ModelState.Clear();
                return View("delload", obj);
            }
            return View("delload", obj);

        }
    }
}

patientregistration/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class loginController : Controller
    {
        clinicEntities dbobj = new clinicEntities();
        // GET: login
        public ActionResult logpageLoad()
        {
            return View();
        }
        public ActionResult log_click(logcls objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.FullName, objcls.Mobile, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    Session["FullName"] = objcls.FullName;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "Invalid login";
                    return View("logpageLoad", objcls);

                }

            }
            return View("logpageLoad", objcls);
        }


        public ActionResult Home()
        {
            return View();
        }
    }
}

patientregistration/Views/Pdelete/delload.cshtml
@model patientregistration.Models.Class4
@{
    ViewBag.Title = "delload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Delete</h2>
<div>
    @using (Html.BeginForm("delload", "Pdelete", FormMethod.Post))
    {
        @*<div>
                <label>PatientID:</label>
            </div>
            <div>
                @Html.TextBoxFor(m => m.PatientID)
                @Html.ValidationMessageFor(m => m.PatientID)
            </div>*@



        <div>
            <label>FullName:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.FullName)
            @Html.ValidationMessageFor(m => m.FullName)
        </div>


        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextAreaFor(m => m.Address)
            @Html.ValidationMessageFor(m => m.Address)
        </div>

        <div>
            <label>PINCode:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.PINCode)
            @Html.ValidationMessageFor(m => m.PINCode)
        </div>

        <div>
            <label>AadharID:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.AadharID)
            @Html.ValidationMessageFor(m => m.AadharID)
        </div>

        <div>
            <label>Mobile:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Mobile)

        </div>


        <div>
            <label>BloodGroup:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.BloodGroup)
            @Html.ValidationMessageFor(m => m.BloodGroup)
        </div>

        <div>
            <label>VisitDate:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.VisitDate)
            @Html.ValidationMessageFor(m => m.VisitDate)
        </div>

        <div>
            <label>Purposeofvisit:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Purposeofvisit)
            @Html.ValidationMessageFor(m => m.Purposeofvisit)
        </div>
        <div>
            <input type="submit" value="Delete" />
            @Html.DisplayFor(m => m.msg)
        </div>

        <div>
            @Html.ActionLink("Back to Home", "Home", "login")


        </div>
    }

</div>