patientregistration/Controllers/PupdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class PupdateController : Controller
    {
        clinicEntities dbobj = new clinicEntities();
        // GET: Pupdate
        public ActionResult Updateload(Class3 obj)
        {
            if (ModelState.IsValid)
            {
                dbobj.sp_update(Session["FullName"].ToString(), obj.VisitDate, obj.PurposeofVisit);
                obj.msg = "Updated";
                ModelState.Clear();
                return View("Updateload", obj);
            }
            return View("Updateload", obj);
        }
    }
}

patientregistration/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class loginController : Controller
    {
        clinicEntities dbobj = new clinicEntities();
        // GET: login
        public ActionResult logpageLoad()
        {
            return View();
        }
        public ActionResult log_click(logcls objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.FullName, objcls.Mobile, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    Session["FullName"] = objcls.FullName;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "Invalid login";
                    return View("logpageLoad", objcls);

                }

            }
            return View("logpageLoad", objcls);
        }


        public ActionResult Home()
        {
            return View();
        }
    }
}

patientregistration/Views/Pupdate/Updateload.cshtml
@model patientregistration.Models.Class3
@{
    ViewBag.Title = "Updateload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>details</h2>
@using (Html.BeginForm("Updateload", "Pupdate", FormMethod.Post))
{
    <div>
        <label>VisitDate:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.VisitDate)
        @Html.ValidationMessageFor(m => m.VisitDate)
    </div>

    <div>
        <label>PurposeofVisit:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.PurposeofVisit)
        @Html.ValidationMessageFor(m => m.PurposeofVisit)
    </div>
    <div>
        <input type="submit" value="Update" />
        @Html.DisplayFor(m => m.msg)
    </div>
    <div>
        @Html.ActionLink("Back to Home", "Home", "login")


    </div>
}