patientregistration/Controllers/PsearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class PsearchController : Controller

    {
        clinicEntities dbobj = new clinicEntities();
        // GET: Psearch
        public ActionResult searchload()
        {
            var getdata = dbobj.sp_search(Session["FullName"].ToString()).FirstOrDefault();
            return View(new Class2 { FullName = getdata.FullName, Address = getdata.Address, PINCode = getdata.PIN_Code, AadharID = getdata.Aadhar_ID_Number, Mobile = getdata.Mobile });


        }
    }
}

patientregistration/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using patientregistration.Models;
namespace patientregistration.Controllers
{
    public class loginController : Controller
    {
        clinicEntities dbobj = new clinicEntities();
        // GET: login
        public ActionResult logpageLoad()
        {
            return View();
        }
        public ActionResult log_click(logcls objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.FullName, objcls.Mobile, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    Session["FullName"] = objcls.FullName;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "Invalid login";
                    return View("logpageLoad", objcls);

                }

            }
            return View("logpageLoad", objcls);
        }


        public ActionResult Home()
        {
            return View();
        }
    }
}

patientregistration/Views/Psearch/searchload.cshtml
@model patientregistration.Models.Class2
@{
    ViewBag.Title = "searchload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
@using (Html.BeginForm("log_click", "Psearch", FormMethod.Post))
{<div>
        <label>FullName:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.FullName)
        @Html.ValidationMessageFor(m => m.FullName)

    </div>

    <div>
        <label>Address:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.Address)
        @Html.ValidationMessageFor(m => m.Address)

    </div>

    <div>
        @Html.TextBoxFor(m => m.PINCode)
        @Html.ValidationMessageFor(m => m.PINCode)
    </div>

    <div>
        <label>AadharID:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.AadharID)
        @Html.ValidationMessageFor(m => m.AadharID)
    </div>



    <div>
        <label>Mobile:</label>
    </div>
    <div>
        @Html.TextBoxFor(m => m.Mobile)


    </div>
    <div>
        @Html.ActionLink("Back to Home", "Home", "login")


    </div>
}